name: Aggiorna Stelline ✨
on:
  workflow_dispatch:
  schedule:
  - cron: 30 0 * * *
jobs:
  stellestelline:
    name: Aggiorna Stelline ✨
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Installa dipendenze
      run: |
        python -m pip install --upgrade pip
        pip install starred
    - name: aggiorna repo
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: starred --username BachoSeven --repository stellestelline --sort --token ${GITHUB_TOKEN} --message 'Aggiornamento periodico delle stelline tramite github action'
